@startuml

:Player: as p

rectangle Tamagotchi {

    p -> (Start App)
    
    package Menu {
        
        p --> (Edit Options)
        p --> (New Game)
        p --> (Chose Save)
        p --> (Login Online)
        
        (Load) ..> (Start Game) : <<include>>
        (New Game) ..> (Choose Pet) : <<include>>
        (Login Online) ..> (Authentification) : <<include>>
        (Login Online) ..> (Load) : <<include>>
        (Chose Save) ..> (Load) : <<include>>
        (Start App) <.. (Load) : <<extend>>\n[if save file]
        (Start App) <.. (New Game) : <<extend>>\n[if no save file]
        (Choose Pet) <.. (Customize Pet) : <<extend>>\n[if player wants]
        (Choose Pet) ..> (Start Game) : <<include>>
        (Edit Options)
    }

    package Game {
    
        p --> (Change Room)
        p --> (Feed)
        p --> (Interact with Pet)
        p --> (Open Menu)
        
        (Change Room) ..> (Change player location) : <<include>>
        (Change Room) ..> (Load environment) : <<include>>
        (State Change) ..> (Save) : <<include>>
        (Give) ..> (State Change) : <<include>>
        (Cook) ..> (Give) : <<include>>
        (Fridge) ..> (Give) : <<include>>
        (Feed) <.. (Cook) : <<extend>>\n[if in kitchen]
        (Feed) <.. (Fridge) : <<extend>>\n[if in kitchen]
        (MiniGame) <.. (Sport) : <<extend>>\n[if outside]
        (Interact with Pet) ..> (State Change) : <<include>>
        (Interact with Pet) <.. (MiniGame) : <<extend>>\n[if player chose]
    }
}

@enduml
