@startuml

hide empty attributes
hide empty methods

class App
interface Lang
App ..> Lang
class Fr
Class En
Lang <|.. Fr
Lang <|.. En

package model {
    class ModelRoom
    class ModelGame
    class ModelStat
    class ModelOption {
	    -Lang lang
	    -Double volume
    }
    interface ModelPet
    class Robot
    class Animal
    
    ModelPet <|.. Robot
    ModelPet <|.. Animal
    ModelPet o-- ModelStat
    ModelGame o-- ModelPet
    ModelGame o-- ModelRoom
}

package view {
	class ViewMain
    class ViewPet
    class ViewRoom
    class ViewStat
    class ViewMenu
    class ViewCustomPet
    class ViewLoad
    class ViewAction
    class ViewOption
    class ViewGame
    class ViewHUD
    
    ViewMain *-- ViewGame
    ViewMain *-- ViewMenu
    ViewMenu *-- ViewOption
    ViewMenu *-- ViewCustomPet
    ViewMenu *-- ViewLoad
    ViewGame *-- ViewHUD
    ViewHUD  *-- ViewAction
    ViewHUD  o-- ViewStat
    ViewGame o-- ViewRoom
    ViewGame o-- ViewPet
}

package Controller {
    class ControllerMain
    
    class ControllerPet {
        -ModelPet
        -ViewPet
    }
    class ControllerRoom {
        -ModelRoom
        -ViewRoom
    }
    class ControllerStat {
        -ModelStat
        -ViewStat
    }
    class ControllerMenu {
        -ModelOption
        -ViewMenu
    }
    class ControllerGame {
        -ModelGame
        -ViewGame
    }
    
    ControllerPet *-- ControllerStat
    ControllerGame *-- ControllerPet
    ControllerGame *-- ControllerRoom
    ControllerMain *-- ControllerGame 
    ControllerMain *-- ControllerMenu
    
}

App *-- ControllerMain

@enduml
